### ISSUE TITLE
fetchImages should accept many arguments

### ISSUE THREAD

**Issue by homm** [Zmoki/fetch-images#1]
The task was (to be precise, in Russian):

> Функция принимает в качестве аргументов любое кол-во в любой комбинации:
> — строки. URL до картинок, которые нужно загрузить.
> — объекты HTMLImageElement, в которые загружены картинки,
>   либо загружаются картинки, либо даже еще не начали загружать картинки
>   (только что созданные с помощью new Image(), у которых src будет установлен
>   после вызова функции).

This means: the function should accept any number of arguments, every of which can be a string or HTMLImageElement. Not the array of arguments.

**Comment by Zmoki** [comment]
@homm fix with commit https://github.com/Zmoki/fetch-images/commit/74ed1837a12ae2810aacfe9b64b061f9e34e7d29
